{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kiss-mail.secretName" . }}
  labels:
    {{- include "kiss-mail.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.apiKey }}
  KISS_MAIL_API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.ldapPassword }}
  KISS_MAIL_LDAP_BIND_PASSWORD: {{ .Values.secrets.ldapPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.ssoClientSecret }}
  KISS_MAIL_SSO_CLIENT_SECRET: {{ .Values.secrets.ssoClientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
